version: "3.8"
name: 'sportspot'

services:
  backend:
    depends_on:
      mongodb:
        condition: service_healthy
      mariadb:
        condition: service_healthy
      cache:
        condition: service_healthy
      azurestorageemulator:
        condition: service_started
    build:
      context: ./SportSpot
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./Development.env
      - ./Subscription.env

  mongodb:
    restart: always
    tty: true
    hostname: "mongodb"
    image: "mongo:latest"
    ports:
      - '27017:27017'
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 60

  mariadb:
    image: mariadb:latest
    hostname: "mariadb"
    environment:
      - MARIADB_DATABASE=Auth
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - maria_data:/data/db
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 5s
      timeout: 5s
      retries: 60

  azurestorageemulator:
    image: "mcr.microsoft.com/azure-storage/azurite@sha256:47a392f1c93a6b639999fc505dcae348e350183b47f2a7526c765ddd7fa56e0e"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  cache:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 5s
      retries: 60
    volumes:
      - cache_data:/data/db

volumes:
  mongo_data:
  maria_data:
  cache_data:
